import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Exo } from "next/font/google";
import StoreFeatures from "@/components/layout/StoreFeatures";
import { Toaster } from "@/components/ui/toast"
import AuthProvider from "@/components/auth/AuthProvider"

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${exo.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Navbar />
          {children}
          <Toaster />
          <StoreFeatures />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
