import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar/page";
import Footer from "./_components/footer/page";
import { Exo } from "next/font/google";
import StoreFeatures from "./_components/StoreFeatures/page";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${exo.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <StoreFeatures />
        <Footer />
      </body>
    </html>
  );
}
